# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24d11cb1c425e623c792e5c1d97de727a6b411ccf3f5b3eb2a9aa03719b40cfd02baf5d17708838184407ef5057b683df22a6fd8fc33a7277bccc28ddb5ea7db

test:
  secret_key_base: 95734b45f325afef947acdf5a0163692e0f0f2385a8dec16301b43b3bedeb478504b89c6cc1c69dbf0c291ec11d73af8fb89c68355465859caaaa6f46a266a9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
